---
title: "Project Work Overview"
author: "Josh Granek"
date: "January 29, 2021"
output:
  ioslides_presentation: default
  beamer_presentation: default
  md_document:
    variant: markdown_github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Projects
## Project Groups {.build}

- **Project 1 - Microbiome adaptation to plastics**
  - Brianna, Derrick, Amani, Katherine M.

- **Project 2 - Personal microbiomes and chemical exposome**
  - Katherine D., Elissa, Yingzhu, Pat

- **Project 3 - The mycobiome of the pig lung**
  - Naveen, Beverly, Zeni

- **Project 4 – 16S amplicon vs shallow shotgun sequencing**
  - Vidya, Eva, Mizpha, Justice

- **Project 5 – Biofouling of solar panels**
  - Sam, Sarah, Aaron, Jessica

# Project Organization

## Class, Group, and Individual
  > - Class: `/data`
  > - Group: `/sharedspace/OurProject`
  > - Individual: `/home/guest`
  
## Name that Location
  - Code?
  - Taxonomic Reference (e.g. Silva)?
  - Raw Data (e.g. FASTQs)?
  - Intermediate Files (e.g. Filtered FASTQs)?
  - Final Results (e.g. RDS of phyloseq object)?
  - Metadata?

## Code {.build}
  - Git Repo in Home directory
  - Remote repository on Github
    - All project members are collaborators

## Taxonomic Reference (e.g. Silva)? {.build}
  - Class: everyone needs these
  - `/data/references`

## Raw Data (e.g. FASTQs)? {.build}
  - Working Copy
    - Group Directory
    - Read Only
  - Archive
    - New Data: Duke Data Service
    - Published Data: SRA

## Intermediate Files (e.g. Filtered FASTQs)? {.build}
  - Individual
  - `/home/guest/scratch/atacama_1pct`

## Final Results (e.g. RDS of phyloseq object)? {.build}
  - Individual: `/home/guest/scratch/atacama_1pct`
  - Group: `/sharedspace/platypus_poop`

## Metadata?  {.build}
  - Data: `/data/projects/platypus_poop`
  - Group: `/sharedspace/platypus_poop`

# Managing Space


## Space: Availabile

```{bash}
df -h
```

## Space: Usage

```{bash}
du -h --max-depth 1 /home/guest
```

## Space: Usage (continued)

```{bash}
du --max-depth 1 /home/guest | sort -nr
```

# Project Timeline
## Milestones
  - February 19: Group Presentations on Project Background
  - March 12: Group Presentations on Project Progress
  - April 9: Poster/Figure Critique
  - April 23:	Final Presentations

# Collaboration

## Collaborating with Git
  - [Collaborating with Git](https://github.com/ibiem-2020/ibiem_2020_material/blob/master/content/lessons/bootcamp/040_git_overview.md#collaborating)

## Git for Teams
  - [Team Conflicts](https://github.com/ibiem-2020/ibiem_2020_material/blob/master/content/lessons/bootcamp/040_git_overview.md#team-conflicts)
  - [Branching](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging)
  - [Stashing](https://git-scm.com/book/en/v2/Git-Tools-Stashing-and-Cleaning)
  - [Tagging](https://git-scm.com/book/en/v2/Git-Basics-Tagging)
